- Developer:
  - Github:
    - abbr: GH
      href: https://github.com/
- Social:
  - Reddit:
    - abbr: RE
      href: https://reddit.com/
- Entertainment:
  - YouTube:
    - abbr: YT
      href: https://youtube.com/
- test1:
  - test1:
    - abbr: ts
      href: https://youtube.com/
  - te:
    - abbr: tt
      href: https://youtube.com/
    - t2:
      - abbr: tt2
        href: https://youtube.com/
  - 项目列表:
    - abbr: tt
      href: https://youtube.com/
  - '123':
    - abbr: '321'
      href: http://test.test
