- Developer:
  - Github:
    - abbr: GH-1
      href: https://github.com/
  - '123':
    - abbr: ts
      href: http://test.test
- Social:
  - Reddit:
    - abbr: RE-1
      href: https://reddit.com/
- Entertainment:
  - YouTube:
    - abbr: YT
      href: https://youtube.com/
